name: Spell Check

on:
  - pull_request
  - push

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spell check
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          skip: ./.git
          ignore_words_file: .github/workflows/codespell-ignore-words-list.txt
